### ISSUE TITLE
[Feature] Implement Do While Loop

### ISSUE THREAD

**Issue by ByteWolf-dev** [Kipper-Lang/Kipper#520] opened 2024-06-24 10:38 UTC
### Is there an existing proposal for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest version

- [X] I am using the latest version

### Proposal

No Proposal yet

### Exact behaviour / changes you want

Implement a basic Do While Loop

**Comment by Luna-Klatzer** [comment] 2024-06-24 10:40
Duplicate of #271.

**Closed as not planned by Luna-Klatzer** 2024-06-24 10:40 UTC
Labels: duplicate, invalid
